spring:
  application:
    name: eureka-server

server:
  port: 1111

eureka:
  instance:
    hostname: peer1
  client:
#    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/