server:
  port: 1111

eureka:
  instance:
    hostname: localhost
  client:
    register-with-rureka: false
    fatch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka